name: Makefile CI

on:
  push:
    branches: [ "android-12.1" ]
  pull_request:
    branches: [ "android-12.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Repo Tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo
              
    - name: Build TWRP
      run: |
        lunch twrp_corvette
        make recoveryimage
      
