name: Makefile CI

on:
  push:
    branches: [ "android-12.1" ]
  pull_request:
    branches: [ "android-12.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build TWRP
      run: |
        cd twrp
        repo init --depth=1 -u https://github.com/TWRP-Test/platform_manifest_twrp_aosp.git -b twrp-16.0
        repo sync
        git clone --depth=1 https://github.com/SakuraKyuo/device_oneplus_corvette-TWRP
        source build/envsetup.sh
        lunch twrp_corvette
        make recoveryimage
      
